# -*- coding: utf-8 -*-
#
#################################################################################
# Author      : Weblytic Labs Pvt. Ltd. (<https://store.weblyticlabs.com/>)
# Copyright(c): 2023-Present Weblytic Labs Pvt. Ltd.
# All Rights Reserved.
#
#
# This program is copyright property of the author mentioned above.
# You can`t redistribute it and/or modify it.
##################################################################################

# -*- coding: utf-8 -*-
import base64
import json
import logging

import requests
from odoo import api, fields, models
from odoo.exceptions import UserError, ValidationError
from odoo.osv.expression import AND, OR

_logger = logging.getLogger(__name__)

MAYA_SUCCESS_SCENARIOS = frozenset([
    'payment_success',
    'one_time_payment_success',
    'payment_paid',
    'paid',
])

MAYA_FAIL_SCENARIOS = frozenset([
    'payment_failed',
    'payment_expired',
    'checkout_failure',
    'one_time_payment_failure',
    'checkout_dropout',
    'one_time_payment_dropout',
    'failed',
    'expired',
    'cancelled',
    'canceled',
])

MAYA_NEUTRAL_SCENARIOS = frozenset([
    'authorized',
    'checkout_success',  # checkout created/redirected is not always paid
])


class PaymentTransaction(models.Model):
    _inherit = 'payment.transaction'

    maya_checkout_id = fields.Char(
        string="Maya Checkout ID",
        readonly=True,
        copy=False,
        index=True,
        help="Checkout identifier generated by Maya.",
    )
    maya_transaction_id = fields.Char(
        string="Maya Transaction ID",
        readonly=True,
        copy=False,
        index=True,
        help="Legacy Maya transaction/checkout identifier.",
    )
    maya_currency = fields.Char(
        string="Maya Currency",
        readonly=True,
        copy=False,
        index=True,
    )
    maya_status = fields.Char(
        string="Maya Status",
        readonly=True,
        copy=False,
        index=True,
    )

    maya_refund_id = fields.Char(
        string="Maya Refund ID",
        readonly=True,
        copy=False,
        index=True,
    )
    maya_refund_currency = fields.Char(
        string="Maya Refund Currency",
        readonly=True,
        copy=False,
    )
    maya_refund_status = fields.Char(
        string="Maya Refund Status",
        readonly=True,
        copy=False,
        index=True,
    )

   

    @api.constrains('maya_checkout_id', 'maya_transaction_id', 'maya_refund_id')
    def _check_maya_identifiers(self):
        for rec in self:
            for field_name in ('maya_checkout_id', 'maya_transaction_id', 'maya_refund_id'):
                value = rec[field_name]

                # Empty Char values are False in Odoo; skip safely
                if not value:
                    continue

                # Defensive type check
                if not isinstance(value, str):
                    raise ValidationError("%s must be a string." % field_name.replace('_', ' ').title())

                if value != value.strip():
                    raise ValidationError("%s cannot have leading or trailing spaces." % field_name.replace('_', ' ').title())


    def _get_specific_rendering_values(self, processing_values):
        self.ensure_one()
        if self.provider_code != 'maya':
            return super()._get_specific_rendering_values(processing_values)

        return {
            'tx': self,
            'tx_url': "/payment/maya/redirect?tx_id=%s" % self.id,
        }

    @api.model
    def _get_tx_from_notification_data(self, provider_code, notification_data):
        """
        Odoo standard hook used by payment flows.
        """
        if provider_code != 'maya':
            return super()._get_tx_from_notification_data(provider_code, notification_data)
        tx = self._maya_resolve_from_webhook_payload(notification_data or {})
        if not tx:
            raise ValidationError("Maya: no matching transaction found for notification.")
        return tx

    @api.model
    def _maya_extract_scenario(self, payload, default_scenario=None):
        """
        Normalize scenario/event value from payload.
        """
        if not isinstance(payload, dict):
            scenario = default_scenario or ''
        else:
            data = payload.get('data') if isinstance(payload.get('data'), dict) else payload
            scenario = (
                default_scenario
                or payload.get('scenario')
                or payload.get('event')
                or payload.get('type')
                or data.get('scenario')
                or data.get('event')
                or data.get('type')
                or data.get('status')
                or payload.get('status')
                or ''
            )

        normalized = (scenario or '').strip().lower()
        normalized = normalized.replace(' ', '_').replace('-', '_').replace('.', '_')
        return normalized

    @api.model
    def _maya_resolve_from_webhook_payload(self, payload):
        """
        Resolve transaction using a single OR domain (review-aware),
        scoped to Maya provider only.
        """
        if not isinstance(payload, dict):
            return self.browse()

        data = payload.get('data') if isinstance(payload.get('data'), dict) else payload

        checkout_id = (
            data.get('checkoutId')
            or data.get('id')
            or payload.get('checkoutId')
            or payload.get('id')
        )
        payment_reference = (
            data.get('paymentTransactionReferenceNo')
            or payload.get('paymentTransactionReferenceNo')
        )
        request_reference = (
            data.get('requestReferenceNumber')
            or payload.get('requestReferenceNumber')
            or data.get('reference')
            or payload.get('reference')
        )

        subdomains = []
        if checkout_id:
            subdomains.append([('provider_reference', '=', checkout_id)])
            subdomains.append([('maya_checkout_id', '=', checkout_id)])
            subdomains.append([('maya_transaction_id', '=', checkout_id)])
        if payment_reference:
            subdomains.append([('provider_reference', '=', payment_reference)])
        if request_reference:
            subdomains.append([('reference', '=', request_reference)])

        if not subdomains:
            return self.browse()

        domain = AND([
            [('provider_id.code', '=', 'maya')],
            OR(subdomains),
        ])

        return self.sudo().search(domain, limit=1, order='id DESC')

    def _maya_apply_webhook_scenario(self, scenario, payload=None):
        """
        Safe webhook state machine:
        - success -> done
        - fail -> canceled (unless already done)
        - neutral/unknown -> pending when still draft
        """
        self.ensure_one()
        payload = payload or {}
        data = payload.get('data') if isinstance(payload.get('data'), dict) else payload

        normalized = self._maya_extract_scenario(payload, default_scenario=scenario)

        vals = {
            'maya_status': normalized or 'webhook_received',
        }

        currency = data.get('currency') or (data.get('amount') or {}).get('currency')
        if currency:
            vals['maya_currency'] = currency

        checkout_id = (
            data.get('checkoutId')
            or data.get('id')
            or payload.get('checkoutId')
            or payload.get('id')
        )
        if checkout_id:
            vals['maya_checkout_id'] = checkout_id
            vals['maya_transaction_id'] = checkout_id

        # Set provider_reference only after verified webhook (not redirect).
        if normalized in MAYA_SUCCESS_SCENARIOS and checkout_id and not self.provider_reference:
            vals['provider_reference'] = checkout_id

        self.write(vals)

        if normalized in MAYA_SUCCESS_SCENARIOS:
            if self.state != 'done':
                self._set_done()
                return 'state_set_done'
            return 'already_done'

        if normalized in MAYA_FAIL_SCENARIOS:
            if self.state == 'done':
                return 'ignored_fail_on_done'
            self._set_canceled()
            return 'state_set_canceled'

        if normalized in MAYA_NEUTRAL_SCENARIOS:
            if self.state == 'draft':
                self._set_pending()
                return 'state_set_pending'
            return 'neutral_no_change'

        # Unknown scenario: keep safe
        if self.state == 'draft':
            self._set_pending()
            return 'unknown_set_pending'
        return 'unknown_no_change'

    def action_maya_refund(self, amount):
        self.ensure_one()

        if self.provider_id.code != 'maya':
            raise UserError("Not a Maya transaction.")

        if not amount or float(amount) <= 0:
            raise UserError("Refund amount must be greater than zero.")

        if self.currency_id.name != 'PHP':
            raise UserError("Maya refund supports PHP only for this integration.")

        provider_ref = self.provider_reference or self.maya_checkout_id or self.maya_transaction_id
        if not provider_ref:
            raise UserError("Missing Maya checkout/reference ID.")

        provider = self.provider_id
        if not provider.maya_secret_key:
            raise UserError("Maya API secret key is not configured.")

        url = "%s/p3/refund" % provider._maya_get_api_base_url()
        timeout = provider.maya_api_timeout or 30

        request_ref_no = "RF-%s-%s" % (
            self.id,
            fields.Datetime.now().strftime("%Y%m%d%H%M%S%f"),
        )

        headers = {
            "Content-Type": "application/json",
            "Authorization": "Basic " + base64.b64encode((provider.maya_secret_key + ":").encode()).decode(),
            "Request-Reference-No": request_ref_no,
        }

        payload = {
            "paymentTransactionReferenceNo": provider_ref,
            "merchant": {
                "metadata": {
                    "refNo": self.reference,
                }
            },
            "amount": {
                "currency": "PHP",
                "value": round(float(amount), 2),
            },
            "reason": "Customer requested refund",
        }

        _logger.info("Maya refund request tx=%s ref=%s", self.id, self.reference)

        try:
            response = requests.post(url, headers=headers, data=json.dumps(payload), timeout=timeout)
        except requests.RequestException:
            _logger.exception("Maya refund API call failed tx=%s", self.id)
            raise UserError("Refund request failed: Maya API unreachable.")

        try:
            result = response.json()
        except ValueError:
            result = {}

        _logger.info("Maya refund response tx=%s status=%s", self.id, response.status_code)

        if response.status_code not in (200, 201):
            raise UserError("Refund failed: %s" % (result.get('message') or response.text))

        self.write({
            "maya_refund_id": result.get("refundId"),
            "maya_refund_status": result.get("status") or result.get("refundStatus") or "requested",
            "maya_refund_currency": (result.get("amount") or {}).get("currency") or "PHP",
        })

        return True

